name: vyuh
repository: https://github.com/vyuh-tech/vyuh

packages:
  - packages/{sanity,system,}/*
  - features/*
  - apps/*

command:
  version:
    workspaceChangelog: false

ide:
  intellij:
    moduleNamePrefix: ''
