name: vyuh
repository: https://github.com/vyuh-tech/vyuh

packages:
  - packages/{sanity,system,plugin,}/*
  - packages/{sanity,system,plugin,}/*/example
  - features/*
  - features/*/*
  - apps/*

command:
  version:
    workspaceChangelog: false
    fetchTags: false
    updateGitTagRefs: false

ide:
  intellij:
    moduleNamePrefix: ''
