name: vyuh_extension_script
description: A scripting extension for the Vyuh Framework
version: 1.0.0-beta.1
homepage: https://vyuh.tech
repository: https://github.com/vyuh-tech/vyuh/tree/main/packages/system/vyuh_extension_script
issue_tracker: https://github.com/vyuh-tech/vyuh/issues

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_js: ^0.8.0
  vyuh_core: ^1.0.0-beta.1
  vyuh_extension_content: ^1.0.0-beta.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
