# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # All the packages are specified by their name and not path.
        # This is because the package is passed to the 'melos exec' command
        package:
          - vyuh_extension_content
          - vyuh_cache
          - vyuh_core
          - vyuh_feature_developer
          - vyuh_feature_system
          - vyuh_extension_script
          - sanity_client
          - flutter_sanity_portable_text
        include:
          - package: sanity_client
            path: packages/sanity
            test: true
          - package: flutter_sanity_portable_text
            path: packages/sanity
            test: true

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
      - name: Install dependencies
        run: |
          dart pub global activate melos
          dart pub get
          dart run melos bs

      - name: Analyze package
        run: melos exec --scope="{{ matrix.package }}" -- dart analyze --fatal-infos

      - name: Run tests
        if: matrix.test
        run: melos exec --scope="{{ matrix.package }}" -- flutter test --coverage

      - name: Upload coverage reports to Codecov
        if: matrix.test
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package }}
          files: ${{ matrix.path }}/${{ matrix.package }}/coverage/lcov.info
          slug: vyuh-tech/vyuh
