name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish_dart_packages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - packages/system/vyuh_extension_content
          - packages/system/vyuh_cache
          - packages/system/vyuh_core
          - packages/system/vyuh_feature_developer
          - packages/system/vyuh_feature_system
          - packages/system/vyuh_extension_script
          - packages/sanity/flutter_sanity_portable_text
          - packages/sanity/sanity_client


    steps:
      - uses: actions/checkout@v3

      - name: Publish if new
        id: publish
        uses: k-paxian/dart-package-publisher@master
        with:
          flutter: true
          relativePath: ${{ matrix.package }}
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          suppressBuildRunner: true
          skipTests: true
          dryRunOnly: false

      - name: Tag commit
        if: steps.publish.outputs.success
        uses: hole19/git-tag-action@master
        env:
          TAG: ${{steps.publish.outputs.package}}-${{steps.publish.outputs.localVersion}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

